name: Deploy Fitbit Function to GCP

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - develop
    paths:
      - "backend/**"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  FUNCTION_NAME: fitbitwebhookhandler
  SOURCE_DIR: backend

jobs:
  deploy-production:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install
        working-directory: ${{ env.SOURCE_DIR }}

      - name: Build
        run: npm run build
        working-directory: ${{ env.SOURCE_DIR }}

      - name: Test and Generate Coverage Report
        run: npm run test:coverage
        working-directory: ${{ env.SOURCE_DIR }}

      - name: Authorize GCP
        uses: "google-github-actions/auth@v2"
        with:
          credentials_json: "${{ secrets.GCP_SA_KEY }}"

      - name: Deploy Cloud Function
        run: |
          gcloud functions deploy ${{ env.FUNCTION_NAME }} \
            --gen2 \
            --region=${{ secrets.FUNCTION_REGION }} \
            --runtime=nodejs20 \
            --source=${{ env.SOURCE_DIR }} \
            --entry-point=fitbitWebhookHandler \
            --trigger-http \
            --allow-unauthenticated \
            --set-env-vars="GCP_PROJECT=${{ secrets.PROJECT_ID }},FITBIT_REDIRECT_URI=${{ secrets.FITBIT_REDIRECT_URI }},FUNCTION_REGION=${{ secrets.FUNCTION_REGION }},FITBIT_CLIENT_ID=${{ secrets.FITBIT_CLIENT_ID }},FITBIT_CLIENT_SECRET=${{ secrets.FITBIT_CLIENT_SECRET }}" \
            --project=${{ secrets.PROJECT_ID }}

      - name: Discord Notification
        if: always()
        uses: appleboy/discord-action@v1.2.0
        with:
          webhook_id: ${{ secrets.DISCORD_WEBHOOK_ID }}
          webhook_token: ${{ secrets.DISCORD_WEBHOOK_TOKEN }}
          message: |
            ${{ job.status == 'success' && 'âœ…' || 'ðŸš¨' }} [${{ job.status }}] ${{ github.repository }} @ ${{ github.ref_name }}
            Workflow: ${{ github.workflow }}
            Run: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}

  deploy-staging:
    if: github.ref == 'refs/heads/develop'
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install
        working-directory: ${{ env.SOURCE_DIR }}

      - name: Build
        run: npm run build
        working-directory: ${{ env.SOURCE_DIR }}

      - name: Test and Generate Coverage Report
        run: npm run test:coverage
        working-directory: ${{ env.SOURCE_DIR }}

      - name: Authorize GCP
        uses: "google-github-actions/auth@v2"
        with:
          credentials_json: "${{ secrets.GCP_SA_KEY }}"

      - name: Deploy Cloud Function
        run: |
          gcloud functions deploy ${{ env.FUNCTION_NAME }} \
            --gen2 \
            --region=${{ secrets.FUNCTION_REGION }} \
            --runtime=nodejs20 \
            --source=${{ env.SOURCE_DIR }} \
            --entry-point=fitbitWebhookHandler \
            --trigger-http \
            --allow-unauthenticated \
            --set-env-vars="GCP_PROJECT=${{ secrets.PROJECT_ID }},FITBIT_REDIRECT_URI=${{ secrets.FITBIT_REDIRECT_URI }},FUNCTION_REGION=${{ secrets.FUNCTION_REGION }},FITBIT_CLIENT_ID=${{ secrets.FITBIT_CLIENT_ID }},FITBIT_CLIENT_SECRET=${{ secrets.FITBIT_CLIENT_SECRET }}" \
            --project=${{ secrets.PROJECT_ID }}

      - name: Discord Notification
        if: always()
        uses: appleboy/discord-action@v1.2.0
        with:
          webhook_id: ${{ secrets.DISCORD_WEBHOOK_ID }}
          webhook_token: ${{ secrets.DISCORD_WEBHOOK_TOKEN }}
          message: |
            ${{ job.status == 'success' && 'âœ…' || 'ðŸš¨' }} [${{ job.status }}] ${{ github.repository }} @ ${{ github.ref_name }}
            Workflow: ${{ github.workflow }}
            Run: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
